import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        height: Platform.OS === 'web' ? '100vh' as any : '100%',
        backgroundColor: '#0a0a0a',
    },
    header: {
        paddingHorizontal: 15,
        paddingVertical: 10,
        backgroundColor: '#0a0a0a',
        borderBottomWidth: 1,
        borderBottomColor: '#222',
        paddingTop: 40,
    },
    headerTop: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    title: {
        fontSize: 20,
        fontWeight: '900',
        color: '#fff',
        textShadowColor: 'rgba(255, 255, 255, 0.5)',
        textShadowOffset: { width: 0, height: 0 },
        textShadowRadius: 10,
        marginBottom: 0,
    },
    headerButtons: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    headerIcon: {
        padding: 5,
        marginLeft: 10,
    },
    mainLayout: {
        flex: 1,
        flexDirection: 'row',
    },
    contentArea: {
        flex: 1,
        flexDirection: 'column',
    },
    sidebar: {
        width: 350,
        borderLeftWidth: 1,
        borderLeftColor: '#333',
        backgroundColor: '#0a0a0a',
        display: 'flex',
        flexDirection: 'column',
    },
    sidebarContent: {
        flex: 1,
    },
    mobileSidebarOverlay: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        top: 0,
        backgroundColor: 'rgba(10,10,10,0.95)',
        zIndex: 100,
        padding: 10,
    },
    closeSidebarButton: {
        padding: 15,
        alignItems: 'center',
        borderTopWidth: 1,
        borderTopColor: '#333',
    },
    statusBar: {
        height: 30,
        backgroundColor: '#050505',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 15,
        borderTopWidth: 1,
    },
    statusLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    statusIndicator: {
        width: 8,
        height: 8,
        borderRadius: 4,
        marginRight: 10,
    },
    statusText: {
        color: '#666',
        fontSize: 10,
        fontWeight: 'bold',
        letterSpacing: 1,
    },
    drawer: {
        position: 'absolute',
        top: 130,
        left: 0,
        right: 0,
        zIndex: 10,
        backgroundColor: 'rgba(10, 10, 10, 0.95)',
        borderBottomWidth: 1,
        borderBottomColor: '#333',
    },
    webViewWrapper: {
        flex: 1,
        backgroundColor: '#111',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.85)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    modalContent: {
        backgroundColor: '#1a1a1a',
        padding: 25,
        borderRadius: 15,
        width: '100%',
        maxWidth: 400,
        borderWidth: 1,
        borderColor: '#444',
        alignItems: 'center',
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#fff',
        marginBottom: 15,
    },
    modalText: {
        color: '#ccc',
        fontSize: 16,
        textAlign: 'center',
        marginBottom: 20,
    },
    modalButton: {
        paddingHorizontal: 30,
        paddingVertical: 12,
        borderRadius: 25,
    },
    modalButtonText: {
        color: '#000',
        fontWeight: 'bold',
        fontSize: 16,
    }
});
