// Feature: Tasks | Why: Styles for layout switcher — variant selector + hierarchical tree panel
import { StyleSheet } from 'react-native';
import { BASE } from '../../../features/ui/theme/ui.primitives';
import { MOBILE } from './mobile-task.styles';

export const switcherStyles = StyleSheet.create({
    row: {
        flexDirection: 'row',
        gap: 6,
        paddingHorizontal: MOBILE.pad,
        paddingVertical: 8,
    },
    option: {
        flex: 1,
        alignItems: 'center',
        paddingVertical: 8,
        borderRadius: MOBILE.radiusSm,
        borderWidth: 1,
        borderColor: BASE.borderFocusStrong,
        gap: 2,
        position: 'relative',
        overflow: 'hidden',
    },
    icon: { fontSize: 16 },
    label: {
        fontSize: 8,
        fontWeight: '800',
        color: BASE.textMuted,
        letterSpacing: 0.6,
    },
    desc: { fontSize: 7, color: BASE.textFaint },
    activeBar: {
        position: 'absolute',
        bottom: 0,
        left: '20%',
        right: '20%',
        height: 2,
        borderRadius: 1,
    },
    treeWrap: {
        marginHorizontal: MOBILE.pad,
        marginBottom: 6,
        backgroundColor: BASE.inputBg,
        borderRadius: MOBILE.radiusSm,
        borderWidth: 1,
        borderColor: BASE.borderSubtle,
        overflow: 'hidden',
    },
    treeScroll: { maxHeight: 180, paddingVertical: 8 },
    missionRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingVertical: 6,
        gap: 8,
    },
    missionOrb: { width: 7, height: 7, borderRadius: 4 },
    missionInfo: { flex: 1 },
    missionTitle: { fontSize: 9, fontWeight: '900', letterSpacing: 0.4 },
    missionMeta: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginTop: 3,
    },
    missionTrack: {
        flex: 1,
        height: 2,
        backgroundColor: 'rgba(255,255,255,0.06)',
        borderRadius: 1,
        overflow: 'hidden',
    },
    missionFill: { height: '100%', borderRadius: 1 },
    missionPct: { fontSize: 8, fontWeight: '800' },
    missionCount: { fontSize: 7, fontWeight: '700', color: BASE.textFaint },
    taskRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingRight: 10,
        height: 24,
    },
    treeLine: {
        width: 28,
        height: 24,
        position: 'relative',
        marginLeft: 12,
    },
    treeVert: { position: 'absolute', left: 3, top: 0, width: 1, height: 12 },
    treeVertFull: { height: 24 },
    treeHoriz: { position: 'absolute', left: 3, top: 12, width: 12, height: 1 },
    taskDot: { fontSize: 8, fontWeight: '800', width: 12, textAlign: 'center' },
    taskTitle: { flex: 1, fontSize: 9, fontWeight: '600', color: BASE.textDim, marginLeft: 4 },
    taskDone: { color: 'rgba(255,255,255,0.25)', textDecorationLine: 'line-through' },
    taskChip: { paddingHorizontal: 5, paddingVertical: 1, borderRadius: 6, marginLeft: 6 },
    taskChipText: { fontSize: 6, fontWeight: '900', letterSpacing: 0.3 },
});
