// Feature: Missions | Trace: src/features/missions/components/MissionOverview.tsx
import { StyleSheet } from 'react-native';

export const missionStyles = StyleSheet.create({
    overlay: { flex: 1, backgroundColor: 'rgba(4,7,12,0.95)' },
    header: { padding: 16, paddingTop: 36, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: 'rgba(185, 205, 230, 0.16)' },
    title: { color: '#e8eefc', fontSize: 18, fontWeight: '900', letterSpacing: 1.2 },
    closeButton: { width: 36, height: 36, borderRadius: 10, backgroundColor: 'rgba(138, 156, 188, 0.12)', justifyContent: 'center', alignItems: 'center' },
    closeText: { color: '#fff', fontSize: 24 },
    content: { padding: 24 },
    section: { marginTop: 20 },
    sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
    sectionTitle: { color: '#7f8ba5', fontSize: 10, fontWeight: '800', letterSpacing: 1.4 },
    routineCard: { backgroundColor: '#101622', borderRadius: 12, padding: 14, marginBottom: 10, borderWidth: 1, borderColor: 'rgba(185, 205, 230, 0.16)' },
    routineHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
    routineName: { color: '#e8eefc', fontSize: 14, fontWeight: '800', letterSpacing: 0.4 },
    routineStat: { color: '#9aa6c0', fontSize: 10, fontWeight: '700' },
    routineGoal: { color: '#c1cee8', fontSize: 12, lineHeight: 17, marginBottom: 10 },
    routineFooter: { flexDirection: 'row', gap: 12 },
    launchBtn: { flex: 1, height: 44, borderRadius: 12, justifyContent: 'center', alignItems: 'center' },
    launchText: { color: '#fff', fontSize: 12, fontWeight: '900', letterSpacing: 1 },
    routineMeta: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 10 },
    metaItem: { color: '#9aa6c0', fontSize: 10, fontWeight: '700' },
    
    // Mission cards
    card: { backgroundColor: '#101622', borderRadius: 12, padding: 14, marginBottom: 10, borderWidth: 1, borderColor: 'rgba(185, 205, 230, 0.16)' },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 12 },
    goal: { color: '#e8eefc', fontSize: 12, fontWeight: '700', letterSpacing: 0.2, flex: 1 },
    taskCountText: { fontSize: 9, fontWeight: '600', marginTop: 3, opacity: 0.7 },
    statusBadge: { backgroundColor: 'rgba(138, 156, 188, 0.12)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, borderWidth: 1, borderColor: 'rgba(185, 205, 230, 0.2)' },
    statusText: { color: '#c1cee8', fontSize: 9, fontWeight: '600' },
    previewContainer: { display: 'none' },
    previewImage: { display: 'none' },
    placeholderPreview: { display: 'none' },
    cardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8, paddingTop: 12 },
    progressText: { color: '#9aa6c0', fontSize: 10, fontWeight: '500' },
    actionText: { color: '#4da3ff', fontSize: 10, fontWeight: '700' },
    container: { flex: 1 },
    tabContainer: { flexDirection: 'row', marginBottom: 14, borderBottomWidth: 1, borderBottomColor: 'rgba(185, 205, 230, 0.16)' },
    tab: { paddingVertical: 10, paddingHorizontal: 12, borderBottomWidth: 2, borderBottomColor: 'transparent' },
    tabText: { color: '#9aa6c0', fontSize: 11, fontWeight: '600' },
    list: { flex: 1 },
});
